#!/bin/sh
# Copyright 2018 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PREREQ=""
prereqs()
{
  echo "$PREREQ"
}
case $1 in
  prereqs)
    prereqs
    exit 0
    ;;
esac

. /scripts/functions
. /scripts/expandroot-lib.sh

kmsg "Resizing partition on ${rootdev}"

if ! rootdev=$(resolve_device "${ROOT}"); then
  kmsg "Failed to resolve root device for \"${ROOT}\""
fi

if ! out=$(split_partition "$rootdev"); then
  kmsg "Failed to detect disk and partition info: ${out}"
  exit 0
fi

disk=${out%:*}
partnum=${out#*:}

if ! parted_needresize "${disk}" "${partnum}"; then
  kmsg "Disk ${rootdev} doesn't need resizing."
  exit 0
fi

if ! out=$(sgdisk_fix_gpt "$disk"); then
  kmsg "Failed to fix GPT: ${out}"
  exit 0
fi

if ! out=$(parted_resizepart "${disk}" "${partnum}"); then
  kmsg "Failed to resize partition: ${out}"
  exit 0
fi

# Ensure the kernel observes the new partition end
reload_partition_table "${disk}"

kmsg "Done"
